#!/bin/bash

if ! command -v pacman &> /dev/null; then
  exit
fi

if ! grep -q chaotic-aur "/etc/pacman.conf"; then
  sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
  sudo pacman-key --lsign-key FBA220DFC880C036
  sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

  sudo echo '[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist' >> /etc/pacman.conf
fi

if ! command -v paru &> /dev/null; then
  sudo pacman -S --noconfirm paru
fi

paru -S --noconfirm \
  base-devel wget curl git zsh tmux neovim fzf exa dust bat \
  spotify-tui spotifyd docker github-cli rust-analyzer
