#!/bin/bash

if ! command -v pacman &> /dev/null; then
  exit
fi

if ! grep -q chaotic-aur "/etc/pacman.conf"; then
  sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com --needed
  sudo pacman-key --lsign-key FBA220DFC880C036 --needed
  sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm --needed

  echo '[chaotic-aur]' | sudo tee -a /etc/pacman.conf > /dev/null
  echo 'Include = /etc/pacman.d/chaotic-mirrorlist' | sudo tee -a /etc/pacman.conf > /dev/null
fi

if ! command -v paru &> /dev/null; then
  sudo pacman -Sy --noconfirm --needed paru
fi

paru -S --noconfirm --needed \
  base-devel wget curl git zsh tmux neovim fzf exa dust bat playerctl pamixer \
  ncspot spotifyd docker github-cli rust-analyzer
