#!/bin/bash

if ! command -v nvm &> /dev/null; then
  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
fi

if ! command -v node &> /dev/null; then
  nvm install --lts
  nvm install node
  nvm use --lts --silent
fi

if ! command -v pnpm &> /dev/null; then
  curl -fsSL https://get.pnpm.io/install.sh | sh -
fi
