#!/bin/bash

if [ ! command -v pyenv &> /dev/null ] && [ ! command -v $HOME/.pyenv/bin/pyenv &> /dev/null ]; then
  echo "Installing Pyenv"
  curl https://pyenv.run | bash
  export PYENV_ROOT="$HOME/.pyenv"
  command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
  echo "Pyenv installed"

  echo "Installing Python with Pyenv"
  PY_VER="$(pyenv install --list | grep -v -e "dev" -e "b" | grep '^  3' | tail -1 | xargs)"
  pyenv install $PY_VER
  pyenv global $PY_VER
  echo "Installed Python with Pyenv"

  echo "Installing pip"
  sudo python -m ensurepip
  sudo python -m pip install wheel
  echo "Pip installed"
fi

if ! command -v $HOME/.local/bin/pipx &> /dev/null; then
  echo "Installing Pipx"
  python -m pip install --user pipx
  python -m pipx ensurepath
  export PATH="$PATH:$HOME/.local/bin"
  echo "Installed Pipx"
else
  echo "Pipx already installed"
fi

if ! command -v $HOME/.local/bin/pipenv &> /dev/null; then
  echo "Installing pipenv"
  $HOME/.local/bin/pipx install pipenv
  echo "Installed pipenv"
else
  echo "Pipenv already installed"
fi
