#!/bin/bash

if ! command -v rustc &> /dev/null; then
  export CARGO_TARGET_DIR=$HOME/.cargo/cache
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile default
  curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
  cargo binstall -y cargo-generate cargo-update cargo-watch cargo-edit cargo-tarpaulin watchexec-cli cargo-outdated 
fi

