#!/bin/bash
pacman -S --noconfirm \
gnome networkmanager gnome-tweaks pipewire flameshot firefox code \
sudo zsh tmux neovim neofetch fzf exa docker \
openssl zlib xz curl base-devel git rust

systemctl enable networkmanager.service
systemctl enable gdm.service

echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
useradd spook --create-home --shell /usr/zsh --groups wheel,networkmanager
su spook

# Install paru
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
pacman -R --noconfirm rust

# Get base dependencies
paru -S --noconfirm \
spotify-tui spotifyd yadm bitwarden-cli \
discord-canary

# Update existing packages and sources
paru --noconfirm


## APP SETUP
# Set up ASDF
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
. $HOME/asdf-vm/asdf.sh
asdf plugin-add dotnet-core https://github.com/emersonsoares/asdf-dotnet-core.git
asdf plugin-add python
asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
asdf plugin-add nodejs
asdf plugin-add java https://github.com/halcyon/asdf-java.git

# Configure tmux
git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm

# Configure neovim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Configure VSCode
code --install-extension ms-python.python

# Set GNOME preferences
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad tap-and-drag-lock true
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'

# Set GNOME shortcuts
dconf load / < keybindings

yadm clone https://github.com/spookdot/dotfiles.git

echo "Please give the user spook a new password"
passwd

echo "Please reboot now"
