#!/bin/bash
pacman -S --noconfirm \
gnome networkmanager gnome-tweaks pipewire flameshot firefox code \
sudo zsh tmux neovim neofetch fzf exa docker \
openssl zlib xz curl base-devel git rust

systemctl enable networkmanager.service
systemctl enable gdm.service

echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
useradd spook -m -s /bin/zsh -G wheel

su spook -c "sh spook_install.sh"

sed '$d' /etc/sudoers
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

# Configure VSCode
code --install-extension ms-python.python

# Set GNOME preferences
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad tap-and-drag-lock true
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'

# Set GNOME shortcuts
dconf load / < keybindings

echo "Please give the user spook a new password"
passwd spook

echo "Please reboot now"
